# Generated by Django 4.1.7 on 2023-02-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userowo', '0002_user_surname_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
