# Generated by Django 4.1.5 on 2023-02-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userowo', '0005_studentsgroup_user_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group',
            new_name='students_group',
        ),
    ]
