# Generated by Django 4.1.7 on 2023-02-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examowo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
