# Generated by Django 4.1.7 on 2023-02-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examowo', '0002_rename_answer_text_answer_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
    ]
