# Generated by Django 4.1.7 on 2023-02-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examowo', '0003_rename_text_answer_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_text',
            new_name='answer_text',
        ),
    ]
