# Generated by Django 4.1.7 on 2023-03-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examowo', '0006_remove_exam_exam_name_exam_block_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='name',
            new_name='exam_name',
        ),
    ]
