# Generated by Django 4.1.7 on 2023-03-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examowo', '0007_rename_name_exam_exam_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_name',
            new_name='name',
        ),
    ]
