# Generated by Django 4.1.7 on 2023-03-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examowo', '0012_rename_exam_name_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examowo.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examowo.question')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(through='examowo.ExamQuestion', to='examowo.question'),
        ),
    ]
