# Generated by Django 4.1.7 on 2023-03-03 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examowo', '0013_remove_question_exam_examquestion_exam_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
