# Generated by Django 4.1.7 on 2023-03-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examowo', '0014_exam_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='access_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
